### ISSUE TITLE
Open file handles?

### ISSUE THREAD

**Issue by alexanderdean** [ninjabear/dr-doom#1]
Is there an interesting test for the number of open files?

**Comment by ninjabear** [comment]
Hey @alexanderdean! I'm not sure I understand what you mean. I think you're asking about unique files, if I open 50 files once, the number of open files is 50. If I open those same files for reading again, I have 100 file handles but only 50 "open files". 

I don't think from the kernels perspective it's interested in the number of open files (asides from IO/caching reasons) only the number of file handles.

I could be wrong! What did you have in mind?

**Comment by alexanderdean** [comment]
Hmm, I think I just meant the number of file handles - is this covered already by `dr-doom`?

**Comment by ninjabear** [comment]
It was in master, but I've just made it official as [v0.2.0](https://github.com/ninjabear/dr-doom/releases/tag/v0.2.0)
